name: OPAM setup and packages installation

inputs:
  ocaml-version:
    description: The OCaml version to be setup
    required: true

runs:
  using: composite
  steps:
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ inputs.ocaml-version }}
        dune-cache: true

    - name: Cache the packages installation
      id: cache-opam
      uses: actions/cache@v4
      with:
        path: _opam
        key: opam-${{ runner.os }}-ocaml-v${{ inputs.ocaml-version }}-${{ hashFiles('dune-project', '.github/**/*') }}
        restore-keys: |
          opam-${{ runner.os }}-ocaml-v${{ inputs.ocaml-version }}-
          opam-${{ runner.os }}-

    - if: steps.cache-opam.outputs.cache-hit != 'true'
      name: Install packages (opam)
      shell: sh
      run: opam install . --deps-only --with-test --with-doc
